### ISSUE TITLE
Interface to the user

### ISSUE THREAD

**Issue by AlexanderMi-BLR** [aontas/XPRising#15]
Please add some life signals to user, to get know how many XP you get, how much needed to next level. 
some progress bar to next level in interface, or type messages in chat each time user getting XP.
or some chat command that will reply current level, current exp / needed to next level. 

Thanks!

P.S.mod making the game much harder, vampire is weakness than a rat. I can't kill even a wolf, now spending 3-4 nights at start graveyard before getting outside, just to take 3 level at least.

**Comment by AlexanderMi-BLR** [comment]
".xp l" called from player seems that I looking for...

**Comment by nerzhei** [comment]
The command `.xp log` toggles XP logging in chat. Be sure to enable it.

**Comment by AlexanderMi-BLR** [comment]
thx it works.
