### ISSUE TITLE
Getting ready for the quest...

### ISSUE THREAD

**Issue by AlexanderMi-BLR** [aontas/XPRising#16]
I assume that is quite problematic to reach 20 lvl by XP levelingto start actually hunting. Can you do something with quest?
![image](https://github.com/aontas/XPRising/assets/52509576/2c982443-3df5-4cb2-b881-3854130d4da7)

Originally you need craft new gear and get bronze sword/spear to complete this quest.

**Comment by AlexanderMi-BLR** [comment]
oh.. .expirence bump20 helped lot, cheating a bit... 
can you change quest objective to reach lvl 8 gear level instead?

**Comment by AlexanderMi-BLR** [comment]
nevermind, it's solved :D

**Comment by AlexanderMi-BLR** [comment]
Sadly, but it is imbalanced. 

.experience bump20 requires short version e,g to type it fast, dot exp bump20 and some option to adjust timeout. 5 seconds is too fast. 

and this is not a solution, there is not only quest. Next after "prepare for hunt" quest requires be 20 lvl to be able to search and kill first v-blood, and everyone who you'll meet will be 9-18 levels. Need to do something with that. 

Playable but feels very hard, everybody can kill you with one shot.

**Comment by aontas** [comment]
I have nothing that will give me the ability to change the requirements of the quest. I don't want to flat-out say that it can't be done, but I haven't seen anything that will allow it. Future mod explorers may give me something I could use.

As for things being too difficult, if you want to have an easier experience, then you should adjust your server settings to support this. That is not something that will be changed by this mod. There are likely other mods out there to support that if you desire.

It is expected that mobs/bosses outside your level range will do more damage to you. It is expected that at the default settings that the player will have to grind to level up to be able to more safely engage higher level mobs/bosses. That is kinda the point of the mod. If you feel that the levelling is too slow, I would recommend increasing the `Multiplier = 1.5` value in the ExperienceConfig.cfg file (and maybe the `Max XP Gain Percent = 50` though this is mostly only relevant for lower levels).

Closing this issue as it will not be solved as suggested.
