### ISSUE TITLE
Hello, I used the red letter displayed on the XPRising server to report an error. Is there any way to solve it?

### ISSUE THREAD

**Issue by tongren66** [aontas/XPRising#18]
![11](https://github.com/aontas/XPRising/assets/148411548/568dae29-7cbe-41eb-9eb6-4179e3bb3bda)

**Comment by aontas** [comment]
Thanks for the report, I'll have a look into it.

**Comment by aontas** [comment]
This should be fixed in v0.1.15. Let me know if there it does not fix your issue.
