### ISSUE TITLE
Want to have people automatically see their XP progress?

### ISSUE THREAD

**Issue by GeniusSlime** [aontas/XPRising#28]
How would I make this a feature?

**Comment by aontas** [comment]
The current main branch (though not yet published to thunderstore) has UI support like this:

![image](https://github.com/user-attachments/assets/fe53348a-770c-4074-8911-5a9e337ce49c)

Is this the sort of thing you are after?

**Comment by aontas** [comment]
Closing as this is released on thunderstore.
