### ISSUE TITLE
Request: Make Mortium kill squads part of Mortium's draculin faction

### ISSUE THREAD

**Issue by Hotklou2404** [aontas/XPRising#31]
Issue: The kill squads from Mortium that come for me when I'm wanted are part of the vampire hunter faction, making them hostile to Mortium enemies even though they themselves are Mortium mobs.

Solution: Make them part of Mortium's own draculin faction so the kill squads from Ruins of Mortium are not hostile to the draculins.

I like the idea of Mortium sending kill squads for me using their own people, but those people should not be hostile to them.

**Comment by aontas** [comment]
Definitely agree. This wanted faction needs some better spawns as well.

**Comment by aontas** [comment]
This should be done now as of v0.3.2.
